name: Build and Deploy to GitHub Pages

on:
  schedule:
    - cron: "0 */4 * * *" # Run every 4 hours
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install Node.js dependencies
        run: pnpm install

      - name: Build TypeScript
        run: pnpm build

      - name: Setup Crawl4AI
        run: uv run crawl4ai-setup

      - name: Restore hn_stories.json cache
        id: cache-stories
        uses: actions/cache@v4
        with:
          path: ./hn_stories.json
          key: ${{ runner.os }}-hn-stories-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-hn-stories-

      - name: Run Python script to generate data
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: uv run src/main.py

      - name: Generate HTML from data
        run: pnpm start ./hn_stories.json ./output

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./output"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
